export const TYPES = {
    ADD_TASK: 'ADD TASK',
    CHANGE_THEME: 'CHANGE THEME',
    COMPLETE_TASK: 'COMPLETE TASK',
    DELETE_TASK: 'DELETE TASK',
    EDIT_TASK: 'EDIT TASK',
    UPDATE_TASK: 'UPDATE TASK'
}